# Generated by Django 3.0.8 on 2020-08-18 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(null=True)),
                ('method', models.TextField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='')),
                ('addedAt', models.DateTimeField(auto_now_add=True)),
                ('recivedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recived', to=settings.AUTH_USER_MODEL)),
                ('sentBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mainUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
